name: Build Android App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Android NDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "ndk;25.2.9519653"
          echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Verify NDK setup
        run: |
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "NDK_HOME: $NDK_HOME"
          ls -la $NDK_HOME || echo "NDK directory not found!"
          echo "Checking Tauri config file:"
          find . -name "tauri.conf.json" -o -name "tauri.conf.*" | xargs ls -la

      - name: Install dependencies
        run: bun install

      - name: Install Tauri CLI
        run: bun install -g @tauri-apps/cli

      - name: Build Android app
        run: |
          # Find the main tauri.conf.json file
          TAURI_CONF=$(find src-tauri -name "tauri.conf.json")
          echo "Found Tauri config at: $TAURI_CONF"

          # Create a backup of the original config
          cp "$TAURI_CONF" "${TAURI_CONF}.backup"

          # Properly set the Android NDK path in the bundle section
          jq --arg ndk "$NDK_HOME" '
            if .bundle == null then . += {"bundle": {}} else . end |
            if .bundle.android == null then .bundle += {"android": {}} else . end |
            .bundle.android += {"ndk": $ndk} |
            .build.beforeDevCommand = "" | 
            .build.beforeBuildCommand = ""
          ' "${TAURI_CONF}.backup" > "$TAURI_CONF"

          # Print the modified config
          echo "Modified Tauri config:"
          cat "$TAURI_CONF"

          # Run the build
          bun run tauri android build --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: src-tauri/gen/android/app/build/outputs/apk/debug/app-debug.apk
