name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios-sim,aarch64-apple-ios

      - name: Install iOS Dependencies
        run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: bun install

      - name: Initialize Tauri iOS
        run: bun run tauri ios init

      - name: Build iOS app for simulator
        run: bun run tauri ios build --debug --target aarch64-sim

      - name: Find simulator build path
        run: |
          echo "Searching for app build directory:"
          find src-tauri -path "*/build/arm64-sim/*.app" -type d | tee app-dir.txt
          echo "APP_DIR=$(find src-tauri -path '*/build/arm64-sim/*.app' -type d | head -n 1)" >> $GITHUB_ENV

      - name: Package app for distribution
        run: |
          if [ -d "${{ env.APP_DIR }}" ]; then
            APP_DIR_PATH="${{ env.APP_DIR }}"
            ZIP_NAME=$(basename "$APP_DIR_PATH" .app)-simulator.zip
            ZIP_PATH=$(dirname "$APP_DIR_PATH")/$ZIP_NAME
            cd $(dirname "$APP_DIR_PATH")
            zip -r "$ZIP_NAME" "$(basename "$APP_DIR_PATH")"
            echo "ZIP_PATH=$ZIP_PATH" >> $GITHUB_ENV
            echo "Created simulator app package at: $ZIP_PATH"
          else
            echo "Error: Could not find iOS simulator app directory"
            exit 1
          fi

      - name: Upload iOS Simulator App
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-debug
          path: ${{ env.ZIP_PATH }}
