name: Build Android App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "ndk;25.2.9519653"
          echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Verify NDK setup
        run: |
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "NDK_HOME: $NDK_HOME"
          ls -la $NDK_HOME || echo "NDK directory not found!"
          echo "Checking Tauri config file:"
          find . -name "tauri.conf.json" -o -name "tauri.conf.*" | xargs ls -la

      - name: Install dependencies
        run: bun install

      - name: Install Tauri CLI
        run: bun install -g @tauri-apps/cli

      - name: Build Android app
        run: |
          # Create a temporary tauri config override
          cat > src-tauri/tauri.conf.json.ndk << EOL
          {
            "android": {
              "ndk": "$NDK_HOME"
            }
          }
          EOL
          # Build with the config override
          bun run tauri android build --debug --config src-tauri/tauri.conf.json.ndk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: src-tauri/gen/android/app/build/outputs/apk/debug/app-debug.apk
