name: Build Android App

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android NDK
        run: sdkmanager --install "ndk;25.2.9519653"

      - name: Install dependencies
        run: bun install

      - name: Initialize Tauri Android
        run: bun run tauri android init

      - name: Build Android app
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/25.2.9519653
          NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/25.2.9519653
        run: bun run tauri android build --debug

      - name: Find APK location
        run: |
          echo "Searching for APK files:"
          find src-tauri -name "*.apk" | tee apk-files.txt
          echo "APK_PATH=$(find src-tauri -name "*.apk" | head -n 1)" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.APK_PATH }}
